spring:
  security:
    user:
      name:
      password:

  datasource:

    url: ${MYSQL_URL}
    driver-class-name: ${MYSQL_DRIVER}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
